### ISSUE TITLE
New integrator class that contains buffers and bond force function 

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/Probabilistic-Peridynamics#67]

**Comment by bb515** [comment]
This has been done. Now `Model`, the cython implementation, is called via the integrator class `Euler`. Similarly, `Model_CL_Ben`, Ben's OpenCL implementation is called via the integrator class `EulerOpenCL`.
Other changes include making sure all the overhead is done when the model object is initialised, so that `model.simulation` only executes a simulation, with only the overhead required to change the simulation parameters.
All changes have been made with 3 things in mind:
- Some OpenCL buffers are unique to the integrator. Therefore it is neater for all OpenCL related python code to live in the integrator classes.
- `model.simulate` should have maximum customisability of parameters (e.g. bond_stiffness, critical_stretch, max_displacement, max_load) without having to re-initiate the model class but should have minimum overhead. This is incase of use for taking samples of simulations or for sensitivity analysis of parameters.
- `model.simulate` should be able to be `paused` and then `played` given the initial states (displacements, forces, etc.)
